var bibtex = {
    'evertz-26-shadows': '<p>@inproceedings{evertz-26-shadows,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Jonathan Evertz and Niklas Risse and Nicolai Neuer and Andreas Müller and Philipp Normann and Gaetano Sapia and Srishti Gupta and David Pape and Soumya Shaw and Devansh Srivastav and Christian Wressnegger and Erwin Quiring and Thorsten Eisenhofer and Daniel Arp and Lea Sch{\\"o}nherr},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Chasing Shadows: Pitfalls in LLM Security Research},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle = {Network and Distributed System Security Symposium (NDSS)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2026}<br>}</p>',

    'bernstein-26-trust': '<p>@inproceedings{bernstein-26-trust,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Shir Bernstein and David Beste and Daniel Ayzenshteyn and Lea Sch{\\"o}nherr and Yisroel Mirsky},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Trust Me, I Know This Function: Hijacking LLM Static Analysis using Bias},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle = {Network and Distributed System Security Symposium (NDSS)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2026}<br>}</p>',

    'holtvennhoff-26-labeling': '<p>@inproceedings{holtvennhoff-26-labeling,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Sandra Höltervennhoff and Jonas Ricker and Maike M Raphael and Charlotte Schwedes and Rebecca Weil and Asja Fischer and Thorsten Holz and Lea Sch{\\"o}nherr and Sascha Fahl},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Security Benefits and Side Effects of Labeling AI-Generated Images},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle = {ACM Conference on Human Factors in Computing Systems (CHI)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2026}<br>}</p>',

    'makarov-26-speech': '<p>@inproceedings{makarov-26-speech,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Rostislav Makarov and Lea Sch{\\"o}nherr and Timo Gerkmann},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Are Modern Speech Enhancement Systems Vulnerable to Adversarial Attacks?},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle = {IEEE International Conference on Acoustics, Speech, and Signal Processing (ICASSP)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2026}<br>}</p>',

    'olivieri-25-smart': '<p>@inproceedings{olivieri-25-smart,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Luca Olivieri and David Beste and Luca Negrini and Lea Sch{\\"o}nherr and Antonio Emanuele Cin{\\`a} and Pietro Ferrara},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Smart Contracts in the Wild: A Study of Smart Contract Vulnerabilities in Real-World Applications},<br>&nbsp;&nbsp;&nbsp;&nbsp;journal = {International Symposium on Software Reliability Engineering (ISSRE)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2025}<br>}</p>',

    'carvalho-25-robust': '<p>@article{carvalho-25-robust,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={João Borges S. Carvalho and Víctor Jiménez Rodríguez and Alessandro Torcinovich and Antonio E Cinà and Carlos Cotrini and Lea Sch{\\"o}nherr and Joachim M Buhmann},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Rethinking Robustness in Machine Learning: A Posterior Agreement Approach},<br>&nbsp;&nbsp;&nbsp;&nbsp;journal = {Transactions on Machine Learning Research (TMLR)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2025}<br>}</p>',

    'debenedetti-24-competition': '<p>@inproceedings{debenedetti-24-competition,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Edoardo Debenedetti and Javier Rando and Daniel Paleka and Silaghi Fineas Florin and Dragos Albastroiu and Niv Cohen and Yuval Lemberg and Reshmi Ghosh and Rui Wen and Ahmed Salem and Giovanni Cherubin and Santiago Zanella-Beguelin and Robin Schmid and Victor Klem and Takahiro Miki and Chenhao Li and Stefan Kraft and Mario Fritz and Florian Tram{\\`e}r and Sahar Abdelnabi and Lea Sch{\\"o}nherr},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Dataset and Lessons Learned from the 2024 SaTML LLM Capture-the-Flag Competition},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle = {NeurIPS Datasets and Benchmarks Track},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2024}<br>}</p>',

    'abdelnabi-24-negotiation': '<p>@inproceedings{abdelnabi-24-negotiation,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Sahar Abdelnabi and Amr Gomaa and Sarath Sivaprasad and Lea Sch{\\"o}nherr and Mario Fritz},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Cooperation, Competition, and Maliciousness: LLM-Stakeholders Interactive Negotiation},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle = {NeurIPS Datasets and Benchmarks Track},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2024}<br>}</p>',

    'destefano-24-rag': '<p>@inproceedings{destefano-24-rag,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Gianluca De Stefano and Lea Sch{\\"o}nherr and Giancarlo Pellegrino},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Rag and Roll: An End-to-End Evaluation of Indirect Prompt Manipulations in LLM-based Application Frameworks},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle = {ArXiv},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2024}<br>}</p>',

    'shaw-24-wild': '<p>@inproceedings{shaw-24-wild,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Soumya Shaw and Ben Nassi and Lea Sch{\\"o}nherr},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Generated Audio Detectors are Not Robust in Real-World Conditions},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle = {ICML Workshop on Next Generation of AI Safety Workshop},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2024}<br>}</p>',

    'gupta-25-build': '<p>@article{gupta-25-build,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Srishti Gupta and Daniele Angioni and Maura Pintor and Ambra Demontis and and Lea Sch{\\"o}nherr and Fabio Roli and Battista Biggio},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={BUILD: Buffer-free Incremental Learning with OOD Detection for the Wild},<br>&nbsp;&nbsp;&nbsp;&nbsp;journal = {Pattern Recognition},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2025}<br>}</p>',

    'beste-25-deobfuscation': '<p>@inproceedings{beste-25-deobfuscation,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={David Beste and Grégoire Menguy and Hossein Hajipour and Mario Fritz and Antonio Emanuele Cin{\\`a} and Sébastien Bardin and Thorsten Holz and Thorsten Eisenhofer and Lea Sch{\\"o}nherr},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Exploring the Potential of LLMs for Code Deobfuscation},<br>&nbsp;&nbsp;&lt;br>booktitle = {Conference on Detection of Intrusions and Malware \\& Vulnerability Assessment (DIMVA)},<br>&lt;br>year={2025}<br>}</p>',

    'acharya-24-imitation': '<p>@inproceedings{acharya-24-imitation,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Bhupendra Acharya and Dario Lazzaro and Efren Lopez-Morales and Adam Oest and Muhammad Saad and Antonio Emanuele Cin{\\`a} and Lea Sch{\\"o}nherr and Thorsten Holz},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={The Imitation Game: Exploring Brand Impersonation Attacks on Social Media Platforms},<br>&nbsp;&nbsp;&lt;br>booktitle = {USENIX Security Symposium},<br>&lt;br>year={2024}<br>}</p>',

    'frank-24-human': '<p>@inproceedings{frank-24-human,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Joel Frank and Franziska Herbert and Jonas Ricker and Lea Sch{\\"o}nherr and Thorsten Eisenhofer and Asja Fischer and Markus D{\\"u}rmuth and Thorsten Holz},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={A Representative Study on Human Detection of Artificially Generated Media Across Countries},<br>&nbsp;&nbsp;&nbsp;&lt;br>&lt;br>booktitle = {IEEE Security and Privacy (S\\&P)},<br>&lt;br>year={2024}<br>}</p>',

    'acharya-24-crypto': '<p>@inproceedings{acharya-24-crypto,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Bhupendra Acharya and Muhammad Saad and Antonio Emanuele Cin{\\`a} and Lea Sch{\\"o}nherr and Hoang Dai Nguyen and Adam Oest and Phani Vadrevu and Thorsten Holz},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Conning the Crypto Conman: End-to-End Analysis of Cryptocurrency-based Technical Support Scams},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle = {IEEE Security and Privacy (S\\&P)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2024}<br>}</p>',

    'hajipour-24-codellm': '<p>@inproceedings{hajipour-24-codellm,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Hossein Hajipour and Keno Hassler and Thorsten Holz and Lea Sch{\\"o}nherr and Mario Fritz},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={CodeLMSec Benchmark: Systematically Evaluating and Finding Security Vulnerabilities in Black-Box Code Language Models},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle = {IEEE Secure and Trustworthy Machine Learning (SatML)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2024}<br>}</p>',
    
    'pape-25-obfuscation': '<p>@inproceedings{pape-25-obfuscation,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={David Pape, Sina Mavali, Thorsten Eisenhofer, and Lea Sch{\\"o}nherr},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Prompt Obfuscation for Large Language Models},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle = {USENIX Security Symposium},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2025}<br>}</p>',

    'hajipour-24-hexacoder': '<p>@inproceedings{hajipour-24-hexacoder,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Hossein Hajipour and Lea Sch{\\"o}nherr and Thorsten Holz and Mario Fritz},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={HexaCoder: Secure Code Generation via Oracle-Guided Synthetic Training Data},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle = {ArXiv},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2024}<br>}</p>',

    'mavali-26-robustfake': '<p>@inproceedings{mavali-26-robustfake,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Sina Mavali and Jonas Ricker and David Pape and Yash Sharma and Asja Fischer and Lea Sch{\\"o}nherr},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Adversarial Robustness of AI-generated Image Detectors in the Real World},<br>&nbsp;&nbsp;&lt;br>booktitle = {Conference on Detection of Intrusions and Malware \\& Vulnerability Assessment (DIMVA)},<br>&lt;br>year={2026}<br>}</p>',
    
    'evertz-26-whisper': '<p>@inproceedings{evertz-26-whisper,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Jonathan Evertz and Merlin Chlosta and Lea Sch{\\"o}nherr and Thorsten Eisenhofer},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Whispers in the Machine: Confidentiality in LLM-integrated Systems},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle = {Conference on Detection of Intrusions and Malware \\& Vulnerability Assessment (DIMVA)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2026}<br>}</p>',
    
    'cina-25-l0': '<p>@inproceedings{cina-25-l0,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Antonio Emanuele Cin{\\`a} and Francesco Villani and Maura Pintor and Lea Sch{\\"o}nherr and Battista Biggio and Marcello Pelillo},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={\sigma-zero: Gradient-based Optimization of l0-norm Adversarial Examples},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle = {International Conference on Learning Representations (ICLR)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2025}<br>}</p>',

    'pape-23-uncertainty': '<p>@inproceedings{pape-23-uncertainty,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={David Pape and Sina D{\\"a}ubener and Thorsten Eisenhofer and Antonio Emanuele Cin{\\`a} and Lea Sch{\\"o}nherr},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={On the Limitations of Model Stealing with Uncertainty Quantification Models},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle = {European Symposium on Artificial Neural Networks, Computational Intelligence and Machine Learning (ESANN)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2023}<br>}</p>',

    'schiller-23-drone': '<p>@inproceedings{schiller-23-drone,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Nico Schiller and Merlin Chlosta and Moritz Schloegel and Nils Bars and Thorsten Eisenhofer and Tobias Scharnowski and Felix Domke and Lea Sch{\\"o}nherr and Thorsten Holz},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Drone Security and the Mysterious Case of DJI’s DroneID},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle = {Network and Distributed System Security Symposium (NDSS)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2023}<br>}</p>',
  
    'aghakhani-23-venomave': '<p>@inproceedings{aghakhani-23-venomave,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Hojjat Aghakhani and Lea Sch{\\"o}nherr and Thorsten Eisenhofer and Dorothea Kolossa and Thorsten Holz and Christopher Kruegel and Giovanni Vign},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={VENOMAVE: Clean-Label Poisoning Against Speech Recognition},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle = {IEEE Secure and Trustworthy Machine Learning (SatML)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2023}<br>}</p>',
  
    'koppelmann-22-privacy': '<p>@inproceedings{koppelmann-22-privacy,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Timm Koppelmann and Luca Beckera and Alexandru Nelus and Rene Glitza and Lea Sch{\\"o}nherr and Rainer Martin},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Clustering-based Wake Word Detection in Privacy-aware Acoustic Sensor Networks},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle={Conference of the International Speech Communication Association (INTERSPEECH)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2023}<br>}</p>',

    'schoenherr-22-unacceptable': '<p>@article{schoenherr-22-unacceptable,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Lea Sch{\\"o}nherr and Maximilian Golla and Thorsten Eisenhofer and Jan Wiele and Dorothea Kolossa and Thorsten Holz},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Unacceptable, where is my privacy? Exploring Accidental Triggers of Smart Speakers},<br>&nbsp;&nbsp;&nbsp;&nbsp;journal = {Computer Speech \&amp; Language},<br>&nbsp;&nbsp;&nbsp;&nbsp;publisher = {Elsevier},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2022}<br>}</p>',

    'frank-21-wavefake': '<p>@inproceedings{frank-21-wavefake,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Joel Frank and Lea Sch{\\"o}nherr },<br>&nbsp;&nbsp;&nbsp;&nbsp;title={WaveFake: A Data Set to Facilitate Audio DeepFake Detection},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle={NeurIPS Datasets and Benchmarks Track},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2021}<br>}</p>',

    'eisenhofer-21-dompteur': '<p>@inproceedings{eisenhofer-21-dompteur,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Thorsten Eisenhofer and Lea Sch{\\"o}nherr and Joel Frank and Lars Speckemeier and Dorothea Kolossa and Thorsten Holz},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Dompteur: Taming Audio Adversarial Examples},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle={USENIX Security Symposium},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2021}<br>}</p>',

    'schoenherr-21-dissertation': '<p>@phdthesis{schoenherr-21-dissertation,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Lea Sch{\\"o}nherr},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Adverarially Robust Speech and Speaker Recognition},<br>&nbsp;&nbsp;&nbsp;&nbsp;school={Ruhr University Bochum},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2021}<br>}</p>',

    'koppelmann-21-privacy': '<p>@inproceedings{koppelmann-21-privacy,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Timm Koppelmann and Alexandru Nelus and Lea Sch{\\"o}nherr and Dorothea Kolossa and Rainer Martin},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Privacy-Preserving Feature Extraction for Cloud-Based Wake Word Verification},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle={Conference of the International Speech Communication Association (INTERSPEECH)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2021}<br>}</p>',

    'frank-20-frequency': '<p>@inproceedings{frank-20-frequency,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Joel Frank and Thorsten Eisenhofer and Lea Sch{\\"o}nherr and Asja Fischer and Dorothea Kolossa and Thorsten Holz},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Leveraging Frequency Analysis for Deep Fake Image Recognition},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle={International Conference on Machine Learning (ICML)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2020}<br>}</p>',

    'schoenherr-20-imperio': '<p>@inproceedings{schoenherr-20-imperio,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Lea Sch{\\"o}nherr and Thorsten Eisenhofer and Steffen Zeiler and Thorsten Holz and Dorothea Kolossa},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Imperio: Robust Over-the-Air Adversarial Examples for Automatic Speech Recognition Systems},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle={Annual Computer Security Applications Conference (ACSAC)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2020}<br>}</p>',

    'daeubener-20-uncertainty': '<p>@inproceedings{daeubener-20-uncertainty,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Sina D{\\"a}ubener and Lea Sch{\\"o}nherr and Asja Fischer and Dorothea Kolossa},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Detecting Adversarial Examples for Speech Recognition via Uncertainty Quantification},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle={Conference of the International Speech Communication Association (INTERSPEECH)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2020}<br>}</p>',

    'freiwald-20-enhancement': '<p>@inproceedings{freiwald-20-enhancement,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Jan Freiwald and Lea Sch{\\"o}nherr and Christopher Schymura and Steffen Zeiler and Dorothea Kolossa},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Loss Functions for Deep Monaural Speech Enhancement},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle={International Joint Conference on Neural Networks (IJCNN)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2020}<br>}</p>',

    'schoenherr-19-psychoacoustic': '<p>@inproceedings{schoenherr-19-psychoacoustic,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Lea Sch{\\"o}nherr and Katharina Kohls and Steffen Zeiler and Thorsten Holz and Dorothea Kolossa},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Adversarial Attacks Against Automatic Speech Recognition Systems via Psychoacoustic Hiding},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle={Symposium on Network and Distributed System Security (NDSS)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2019}<br>}</p>',

    'schoenherr-17-spoofing': '<p>@inproceedings{schoenherr-17-spoofing,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Lea Sch{\\"o}nherr and Steffen Zeiler and Dorothea Kolossa},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Spoofing detection via simultaneous verification of audio-visual synchronicity and transcription},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle={IEEE Automatic Speech Recognition and Understanding Workshop (ASRU)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2017}<br>}</p>',

    'schoenherr-16-audiovisual': '<p>@inproceedings{schoenherr-16-audiovisual,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Lea Sch{\\"o}nherr and Dennis Orth and Martin Heckmann and Dorothea Kolossa},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Environmentally robust audio-visual speaker identification},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle={IEEE Spoken Language Technology Workshop (SLT)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2016}<br>}</p>',
}
