var bibtex = {

    'frank-24-human': '<p>@inproceedings{frank-24-human,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Bhupendra Acharya, Muhammad Saad, Antonio Emanuele Cinà, Lea Sch{\\"o}nherr, Hoang Dai Nguyen, Adam Oest, Phani Vadrevu, Thorsten Holz},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={A Representative Study on Human Detection of Artificially Generated Media Across Countries},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle = {IEEE Security and Privacy (S\&P)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2024}<br>}</p>',

    'acharya-24-crypto': '<p>@inproceedings{acharya-24-crypto,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Joel Frank, Franziska Herbert, Jonas Ricker, Lea Sch{\\"o}nherr, Thorsten Eisenhofer, Asja Fischer, Markus D{\\"u}rmuth, Thorsten Holz},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Conning the Crypto Conman: End-to-End Analysis of Cryptocurrency-based Technical Support Scams},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle = {IEEE Security and Privacy (S\&P)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2024}<br>}</p>',

    'hajipour-24-codellm': '<p>@inproceedings{hajipour-24-codellm,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Hossein Hajipour, Thorsten Holz, Lea Sch{\\"o}nherr, Mario Fritz},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={CodeLMSec Benchmark: Systematically Evaluating and Finding Security Vulnerabilities in Black-Box Code Language Models},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle = {Secure and Trustworthy Machine Learning (SatML)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2024}<br>}</p>',

    'evertz-24-whisper': '<p>@inproceedings{evertz-24-whisper,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Jonathan Evertz, Merlin Chlosta, Lea Sch{\\"o}nherr, Thorsten Eisenhofer},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Whispers in the Machine: Confidentiality in LLM-integrated Systems},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle = {ArXiv},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2024}<br>}</p>',
    
    'cina-24-l0': '<p>@inproceedings{cina-24-l0,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Antonio Emanuele Cin{\\`a}, Francesco Villani, Maura Pintor, Lea Schö{\\"o}nherr, Battista Biggio, Marcello Pelillo},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={\sigma-zero: Gradient-based Optimization of l0-norm Adversarial Examples},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle = {ArXiv},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2024}<br>}</p>',

    'pape-23-uncertainty': '<p>@inproceedings{pape-23-uncertainty,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={David Pape, Sina D{\\"a}ubener, Thorsten Eisenhofer, Antonio Emanuele Cin{\\`a}, Lea Sch{\\"o}nherr},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={On the Limitations of Model Stealing with Uncertainty Quantification Models},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle = {European Symposium on Artificial Neural Networks, Computational Intelligence and Machine Learning (ESANN)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2023}<br>}</p>',

    'schiller-23-drone': '<p>@inproceedings{schiller-23-drone,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Nico Schiller, Merlin Chlosta, Moritz Schloegel, Nils Bars, Thorsten Eisenhofer, Tobias Scharnowski, Felix Domke, Lea Sch{\\"o}nherr, Thorsten Holz},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Drone Security and the Mysterious Case of DJI’s DroneID},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle = {Network and Distributed System Security Symposium (NDSS)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2023}<br>}</p>',
  
    'aghakhani-23-venomave': '<p>@inproceedings{aghakhani-23-venomave,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Hojjat Aghakhani, Thorsten Eisenhofer, Lea Sch{\\"o}nherr, Dorothea Kolossa, Thorsten Holz, Christopher Kruegel, and Giovanni Vign},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={VENOMAVE: Clean-Label Poisoning Against Speech Recognition},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle = {Secure and Trustworthy Machine Learning (SatML)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2023}<br>}</p>',
  
    'abdelnabi-23-negotiation': '<p>@inproceedings{abdelnabi-23-negotiation,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Sahar Abdelnabi, Amr Gomaa, Sarath Sivaprasad, Lea Sch{\\"o}nherr, Mario Fritz},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={LLM-Deliberation: Evaluating LLMs with Interactive Multi-Agent Negotiation Games},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle = {ArXiv},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2024}<br>}</p>',

    'koppelmann-22-privacy': '<p>@inproceedings{koppelmann-22-privacy,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Timm Koppelmann and Luca Beckera and Alexandru Nelus and Rene Glitza and Lea Sch{\\"o}nherr and Rainer Martin},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Clustering-based Wake Word Detection in Privacy-aware Acoustic Sensor Networks},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle={Conference of the International Speech Communication Association (INTERSPEECH)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2023}<br>}</p>',

    'schoenherr-22-unacceptable': '<p>@article{schoenherr-22-unacceptable,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Lea Sch{\\"o}nherr and Maximilian Golla and Thorsten Eisenhofer and Jan Wiele and Dorothea Kolossa and Thorsten Holz},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Unacceptable, where is my privacy? Exploring Accidental Triggers of Smart Speakers},<br>&nbsp;&nbsp;&nbsp;&nbsp;journal = {Computer Speech \&amp; Language},<br>&nbsp;&nbsp;&nbsp;&nbsp;publisher = {Elsevier},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2022}<br>}</p>',

    'frank-21-wavefake': '<p>@inproceedings{frank-21-wavefake,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Joel Frank and Lea Sch{\\"o}nherr },<br>&nbsp;&nbsp;&nbsp;&nbsp;title={WaveFake: A Data Set to Facilitate Audio DeepFake Detection},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle={NeurIPS Datasets and Benchmarks Track},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2021}<br>}</p>',

    'eisenhofer-21-dompteur': '<p>@inproceedings{eisenhofer-21-dompteur,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Thorsten Eisenhofer and Lea Sch{\\"o}nherr and Joel Frank and Lars Speckemeier and Dorothea Kolossa and Thorsten Holz},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Dompteur: Taming Audio Adversarial Examples},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle={USENIX Security Symposium},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2021}<br>}</p>',

    'schoenherr-21-dissertation': '<p>@phdthesis{schoenherr-20-dissertation,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Lea Sch{\\"o}nherr},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Adverarially Robust Speech and Speaker Recognition},<br>&nbsp;&nbsp;&nbsp;&nbsp;school={Ruhr University Bochum},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2021}<br>}</p>',

    'koppelmann-21-privacy': '<p>@inproceedings{koppelmann-21-privacy,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Timm Koppelmann and Alexandru Nelus and Lea Sch{\\"o}nherr and Dorothea Kolossa and Rainer Martin},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Privacy-Preserving Feature Extraction for Cloud-Based Wake Word Verification},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle={Conference of the International Speech Communication Association (INTERSPEECH)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2021}<br>}</p>',

    'frank-20-frequency': '<p>@inproceedings{frank-20-frequency,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Joel Frank and Thorsten Eisenhofer and Lea Sch{\\"o}nherr and Asja Fischer and Dorothea Kolossa and Thorsten Holz},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Leveraging Frequency Analysis for Deep Fake Image Recognition},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle={International Conference on Machine Learning (ICML)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2020}<br>}</p>',

    'schoenherr-20-imperio': '<p>@inproceedings{schoenherr-20-imperio,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Lea Sch{\\"o}nherr and Thorsten Eisenhofer and Steffen Zeiler and Thorsten Holz and Dorothea Kolossa},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Imperio: Robust Over-the-Air Adversarial Examples for Automatic Speech Recognition Systems},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle={Annual Computer Security Applications Conference (ACSAC)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2020}<br>}</p>',

    'daeubener-20-uncertainty': '<p>@inproceedings{daeubener-20-uncertainty,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Sina D{\\"a}ubener and Lea Sch{\\"o}nherr and Asja Fischer and Dorothea Kolossa},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Detecting Adversarial Examples for Speech Recognition via Uncertainty Quantification},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle={Conference of the International Speech Communication Association (INTERSPEECH)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2020}<br>}</p>',

    'freiwald-20-enhancement': '<p>@inproceedings{freiwald-20-enhancement,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Jan Freiwald and Lea Sch{\\"o}nherr and Christopher Schymura and Steffen Zeiler and Dorothea Kolossa},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Loss Functions for Deep Monaural Speech Enhancement},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle={International Joint Conference on Neural Networks (IJCNN)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2020}<br>}</p>',

    'schoenherr-19-psychoacoustic': '<p>@inproceedings{schoenherr-19-psychoacoustic,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Lea Sch{\\"o}nherr and Katharina Kohls and Steffen Zeiler and Thorsten Holz and Dorothea Kolossa},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Adversarial Attacks Against Automatic Speech Recognition Systems via Psychoacoustic Hiding},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle={Symposium on Network and Distributed System Security (NDSS)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2019}<br>}</p>',

    'schoenherr-17-spoofing': '<p>@inproceedings{schoenherr-17-spoofing,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Lea Sch{\\"o}nherr and Steffen Zeiler and Dorothea Kolossa},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Spoofing detection via simultaneous verification of audio-visual synchronicity and transcription},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle={IEEE Automatic Speech Recognition and Understanding Workshop (ASRU)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2017}<br>}</p>',

    'schoenherr-16-audiovisual': '<p>@inproceedings{schoenherr-16-audiovisual,<br>&nbsp;&nbsp;&nbsp;&nbsp;author={Lea Sch{\\"o}nherr and Dennis Orth and Martin Heckmann and Dorothea Kolossa},<br>&nbsp;&nbsp;&nbsp;&nbsp;title={Environmentally robust audio-visual speaker identification},<br>&nbsp;&nbsp;&nbsp;&nbsp;booktitle={IEEE Spoken Language Technology Workshop (SLT)},<br>&nbsp;&nbsp;&nbsp;&nbsp;year={2016}<br>}</p>',
}
